global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: docker
    scrape_interval: 15s
    static_configs: 
      - targets: 
        - "host.docker.internal:9323"
  - job_name: django
    scrape_interval: 15s
    static_configs:
      - targets: 
        - web:8000
        # - 127.0.0.1:8000
 